config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
  @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<p class="navbar navbar-light" style="background-color: #e3f2fd;">simple airbnb</p>
<h1> All our flats </h1>

<div class="container">
  <div class="row">
    <%= @flats.each do |f| %>
      <div class="col-md-4">
        <div class="card">
          <h5>Name: <%= f.name%></h5>
          <p><%= f.address%></p>
          <p><%= f.description%></p>

          <p>
            <i class="fa-solid fa-money-bill"></i>
            price:<%= f.price_per_night%>
            <i class="fa-solid fa-person"></i><i class="fa-solid fa-person"></i>
            number of guests: <%= f.number_of_guests%>
          </p>

          <div>
            <%= link_to "More info", flat_path(f), class: "text-primary" %>
            <%= link_to "Edit", edit_flat_path(f), class: "text-warning" %>
            <%= link_to "Remove", flat_path(f), method: :delete, data: { confirm: "Are you sure?" }, class: "text-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>